repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/realm/SwiftLint
    rev: 0.61.0
    hooks:
      - id: swiftlint
        args: [--lenient] # [--strict]
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.58.2
    hooks:
      - id: swiftformat
