[package]
name = "bench-nucleo"
version = "0.1.0"
edition = "2021"

[dependencies]
nucleo-matcher = "0.3"

[[bin]]
name = "bench-nucleo"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
